apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}
  {{ if .Values.service.create }}
  type: {{ .Values.service.type }}
  {{ end }}
